version: "3.8"

services:

  postgresql:
    image: postgres:14.5
    container_name: postgresql

    volumes:
      - ./data/db:/home/postgresql/data

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ocr
    ports:
      - "5433:5432"


  pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: pgadmin4

    volumes:
      - ./data/pgamin-data:/home/pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"