version: "3.8"

services:

  ocr-app:
    container_name: ocr_app
    image: ocr-image:latest
    build:
      dockerfile: Dockerfile
      context: ./
    networks: ['net']
    ports:
      - "8080:8080"


  postgresql:
    image: postgres:14.5
    container_name: postgresql
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ocr
    ports:
      - "5433:5432"
    networks: ['net']


  pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: pgadmin4

    volumes:
      - ./data/pgamin-data:/home/pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks: ['net']
networks:
  net:
    driver: bridge