
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/ocr
    username: admin
    password: admin
---

spring:
  r2dbc:
    url: r2dbc:tc:postgresql:///testdb?TC_IMAGE_TAG=14-alpine
  config:
    activate:
      on-profile: test


---